export enum KeyboardKeys {
    // System keys
    SYS_NEXT_LOCALE,
    // Service keys
    SHIFT = 'shift',
    BACK_SPACE = 'backspace',
    SPACE = 'space',
    ENTER = 'enter',
    // Latin
    A = 'A',
    B = 'B',
    C = 'C',
    D = 'D',
    E = 'E',
    F = 'F',
    G = 'G',
    H = 'H',
    I = 'I',
    J = 'J',
    K = 'K',
    L = 'L',
    M = 'M',
    N = 'N',
    O = 'O',
    P = 'P',
    Q = 'Q',
    R = 'R',
    S = 'S',
    T = 'T',
    U = 'U',
    X = 'X',
    W = 'W',
    V = 'V',
    Y = 'Y',
    Z = 'Z',
}