import {
    DEFAULT_KEYBOARD_HORIZONTAL_PRESET, DEFAULT_KEYBOARD_LOCALE, DEFAULT_KEYBOARD_POSITION,
    DEFAULT_KEYBOARD_SETTINGS, DEFAULT_KEYBOARD_VERTICAL_PRESET,
} from './keyboard';

export {
    DEFAULT_KEYBOARD_HORIZONTAL_PRESET, DEFAULT_KEYBOARD_LOCALE, DEFAULT_KEYBOARD_POSITION,
    DEFAULT_KEYBOARD_SETTINGS, DEFAULT_KEYBOARD_VERTICAL_PRESET,
}
